quarkus.http.port=8888
quarkus.log.file.enable=true
quarkus.log.file.path=logs/rootlog.log
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.restUser=changeit
quarkus.security.users.embedded.roles.restUser=restUser
%dev.quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.devservices.enabled=false
